baseurl = "http://victortoso.com/"
languageCode = "en-us"
theme = "after-dark"
title = "Victor Toso"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
